## Dataset 

In this assignment you will be working with the "MovieLens dataset". The dataset contains users ratings of thousands of motion pictures collected by MovieLens, a movie recommendation service.

The dataset is in one single file, *movielens.csv*. Each row in the dataset represents a rating provided by the user for a movie at a given time. The following are the description of each column 

* **userId** - The user identifier who provided the rating
* **movieId** - The movie identifier 
* **rating** - The star rating for the movie. Ranging from half a star to five stars
* **timestamp** - The date and time when the rating was provided
* **title** - Name of the movie
* **genres** - The movie genre
* **year** - the year the movie was released 
* **decade** - the decade the movie was released

In [1]:
# SETUP. RUN THIS CELL BUT DO NOT CHANGE.
import numpy as np
import pandas as pd

movielens = pd.read_csv("http://www3.nd.edu/~jng2/movielens.csv", encoding='latin-1')

In [2]:
movielens.head()

,userId,movieId,rating,timestamp,title,genres,year,decade
0,1,31,2.5,2009-12-14 02:52:24,Dangerous Minds,Drama,1995,1990s
1,1,1029,3.0,2009-12-14 02:52:59,Dumbo,Animation,1941,1940s
2,1,1029,3.0,2009-12-14 02:52:59,Dumbo,Children,1941,1940s
3,1,1029,3.0,2009-12-14 02:52:59,Dumbo,Drama,1941,1940s
4,1,1029,3.0,2009-12-14 02:52:59,Dumbo,Musical,1941,1940s

In [3]:
# PROBLEM 1
# Compute the average rating by genre and do these two things: 
# 1) assign it to a Series object named averagerating
# 2) rename the series as avg_rating_by_genre
# Print the result to screen.

#
# YOUR CODE HERE
#
averagerating = movielens.groupby('genres')['rating'].mean().rename('avg_rating_by_genre')
averagerating

genres
(no genres listed)    3.843750
Action                3.445613
Adventure             3.520393
Animation             3.636062
Children              3.466187
Comedy                3.445964
Crime                 3.679639
Documentary           3.813180
Drama                 3.681814
Fantasy               3.518063
Film-Noir             3.955702
Horror                3.315557
IMAX                  3.571134
Musical               3.598793
Mystery               3.679696
Romance               3.556165
Sci-Fi                3.460430
Thriller              3.518603
War                   3.817214
Western               3.566423
Name: avg_rating_by_genre, dtype: float64

In [4]:
# PROBLEM 2
# Merge the averagerating Series and movielens DataFrame as a new DataFrame called movielens2.

# The tricky part here is figuring out what to join on. 
# Hint: you can mix left_on and right_index (or vice-versa)

#
# YOUR CODE HERE
#
movielens2 = pd.merge(movielens,pd.DataFrame(averagerating),left_on='genres',right_index=True)
movielens2.sort_values(by=['movieId'])

,userId,movieId,rating,timestamp,title,genres,year,decade,avg_rating_by_genre
89308,237,1,3.0,2004-12-02 17:47:12,Toy Story,Comedy,1995,1990s,3.445964
155316,418,1,3.5,2005-11-16 22:38:11,Toy Story,Comedy,1995,1990s,3.445964
122181,318,1,1.0,1997-05-06 07:10:04,Toy Story,Fantasy,1995,1990s,3.518063
122572,321,1,3.0,1999-10-08 22:13:58,Toy Story,Fantasy,1995,1990s,3.518063
122952,324,1,4.0,2015-12-31 01:17:28,Toy Story,Fantasy,1995,1990s,3.518063
123715,328,1,4.0,2006-05-18 23:48:26,Toy Story,Fantasy,1995,1990s,3.518063
124249,329,1,5.0,1997-06-23 13:20:04,Toy Story,Fantasy,1995,1990s,3.518063
124709,333,1,4.0,2015-09-02 12:37:51,Toy Story,Fantasy,1995,1990s,3.518063
124933,334,1,5.0,2015-11-09 01:18:07,Toy Story,Fantasy,1995,1990s,3.518063
125105,336,1,2.0,2001-07-22 18:36:16,Toy Story,Fantasy,1995,1990s,3.518063
126281,343,1,5.0,1997-12-03 16:26:37,Toy Story,Fantasy,1995,1990s,3.518063
126394,344,1,4.0,1997-01-20 05:05:11,Toy Story,Fantasy,1995,1990s,3.518063
207922,542,1,4.5,2015-02-26 15:48:25,Toy Story,Children,1995,1990s,3.466187
126854,345,1,4.5,2005-01-28 21:52:50,Toy Story,Fantasy,1995,1990s,3.518063
207663,538,1,5.0,1996-05-11 17:27:50,Toy Story,Children,1995,1990s,3.466187
154926,417,1,3.5,2005-04-04 03:39:53,Toy Story,Comedy,1995,1990s,3.445964
128660,350,1,4.0,2001-11-16 19:28:07,Toy Story,Fantasy,1995,1990s,3.518063
129449,353,1,3.5,2005-03-31 11:31:47,Toy Story,Fantasy,1995,1990s,3.518063
130948,354,1,5.0,1996-10-23 09:23:27,Toy Story,Fantasy,1995,1990s,3.518063
131107,355,1,3.0,2005-10-23 21:55:29,Toy Story,Fantasy,1995,1990s,3.518063
121404,314,1,2.0,2015-07-19 20:34:51,Toy Story,Fantasy,1995,1990s,3.518063
120568,313,1,4.0,2005-01-10 10:56:20,Toy Story,Fantasy,1995,1990s,3.518063
119852,312,1,5.0,2000-06-02 08:06:40,Toy Story,Fantasy,1995,1990s,3.518063
117405,311,1,3.0,1998-06-16 14:37:10,Toy Story,Fantasy,1995,1990s,3.518063
100429,268,1,5.0,2011-09-01 16:21:08,Toy Story,Fantasy,1995,1990s,3.518063
215676,553,1,4.0,2015-02-04 00:53:12,Toy Story,Children,1995,1990s,3.466187
102571,272,1,4.0,2016-01-23 22:19:50,Toy Story,Fantasy,1995,1990s,3.518063
102714,273,1,4.5,2016-06-26 12:52:44,Toy Story,Fantasy,1995,1990s,3.518063
103163,275,1,5.0,2012-10-14 22:35:17,Toy Story,Fantasy,1995,1990s,3.518063
104534,282,1,4.0,2005-03-22 12:16:13,Toy Story,Fantasy,1995,1990s,3.518063
...,...,...,...,...,...,...,...,...,...
107606,287,160563,4.0,2016-07-22 04:24:04,The Legend of Tarzan,Action,2016,2010s,3.445613
7029,15,160565,2.0,2016-07-24 03:17:46,The Purge: Election Year,Sci-Fi,2016,2010s,3.460430
7027,15,160565,2.0,2016-07-24 03:17:46,The Purge: Election Year,Action,2016,2010s,3.445613
7028,15,160565,2.0,2016-07-24 03:17:46,The Purge: Election Year,Horror,2016,2010s,3.315557
7030,15,160567,4.0,2016-07-24 03:17:22,Mike & Dave Need Wedding Dates,Comedy,2016,2010s,3.445964
23219,56,160590,5.0,2016-06-28 06:36:29,Survive and Advance,(no genres listed),2013,2010s,3.843750
214520,547,160656,3.5,2016-08-14 09:54:26,Tallulah,Drama,2016,2010s,3.681814
214521,547,160718,4.0,2016-07-28 13:39:11,Piper,Animation,2016,2010s,3.636062
214522,547,161084,2.5,2016-07-11 14:45:31,My Friend Rockefeller,Documentary,2015,2010s,3.813180
7031,15,161155,0.5,2016-07-24 03:18:27,Sunspring,Sci-Fi,2016,2010s,3.460430
31601,73,161594,3.0,2016-09-19 03:24:19,Kingsglaive: Final Fantasy XV,Adventure,2016,2010s,3.520393
31600,73,161594,3.0,2016-09-19 03:24:19,Kingsglaive: Final Fantasy XV,Action,2016,2010s,3.445613
31604,73,161594,3.0,2016-09-19 03:24:19,Kingsglaive: Final Fantasy XV,Fantasy,2016,2010s,3.518063
31602,73,161594,3.0,2016-09-19 03:24:19,Kingsglaive: Final Fantasy XV,Animation,2016,2010s,3.636062
31605,73,161594,3.0,2016-09-19 03:24:19,Kingsglaive: Final Fantasy XV,Sci-Fi,2016,2010s,3.460430
31603,73,161594,3.0,2016-09-19 03:24:19,Kingsglaive: Final Fantasy XV,Drama,2016,2010s,3.681814
252729,624,161830,1.0,2016-08-29 17:50:10,Body,Thriller,2015,2010s,3.518603
252728,624,161830,1.0,2016-08-29 17:50:10,Body,Horror,2015,2010s,3.315557
252727,624,161830,1.0,2016-08-29 17:50:10,Body,Drama,2015,2010s,3.681814
252732,624,161918,1.5,2016-09-03 19:11:13,Sharknado 4: The 4th Awakens,Horror,2016,2010s,3.315557
252731,624,161918,1.5,2016-09-03 19:11:13,Sharknado 4: The 4th Awakens,Adventure,2016,2010s,3.520393
252730,624,161918,1.5,2016-09-03 19:11:13,Sharknado 4: The 4th Awakens,Action,2016,2010s,3.445613
252733,624,161918,1.5,2016-09-03 19:11:13,Sharknado 4: The 4th Awakens,Sci-Fi,2016,2010s,3.460430
107608,287,161944,5.0,2016-08-02 19:57:04,The Last Brickmaker in America,Drama,2001,2000s,3.681814
244858,611,162542,5.0,2016-08-18 11:44:27,Rustom,Romance,2016,2010s,3.556165
244859,611,162542,5.0,2016-08-18 11:44:27,Rustom,Thriller,2016,2010s,3.518603
244862,611,162672,3.0,2016-08-18 12:39:46,Mohenjo Daro,Romance,2016,2010s,3.556165
244860,611,162672,3.0,2016-08-18 12:39:46,Mohenjo Daro,Adventure,2016,2010s,3.520393
244861,611,162672,3.0,2016-08-18 12:39:46,Mohenjo Daro,Drama,2016,2010s,3.681814
214523,547,163949,5.0,2016-10-14 04:27:19,The Beatles: Eight Days a Week - The Touring Y...,Documentary,2016,2010s,3.813180

In [9]:
# PROBLEM 3
# Using the movielens2 DataFrame you created above, tell me how many UNIQUE movies are above average for their genre. 
# That is, get a count of UNIQUE movies with ratings > avg_rating_by_genre.

#
# YOUR CODE HERE
#
def average_count(df):
    return df[df['rating']>df['avg_rating_by_genre']]['movieId'].nunique()
#6701
average_count(movielens2)

6701

In [6]:
# PROBLEM 4
# Notice that some movies fall into multiple genres. Use DataFrameGroupBy's filter() to generate a new dataframe 
# containing movies that have ONLY ONE GENRE. The new DataFrame must meet these criteria:
# - each movie must be unique
# - the DataFrame must only contain these four columns: movieId, title, genres, year
# - the DataFrame must be sorted in ascending order of movieId 

#
# YOUR CODE HERE
#
def genre_one(df_id):
    if len(df_id['genres'].unique()) == 1:
        return True
    else:
        return False
unique_genres_movies = movielens[['movieId', 'title', 'genres', 'year']].groupby('movieId').filter(genre_one).sort_values(by=['movieId']).drop_duplicates().reset_index(drop = True)
unique_genres_movies

,movieId,title,genres,year
0,5,Father of the Bride Part II,Comedy,1995
1,9,Sudden Death,Action,1995
2,14,Nixon,Drama,1995
3,18,Four Rooms,Comedy,1995
4,19,Ace Ventura: When Nature Calls,Comedy,1995
5,26,Othello,Drama,1995
6,31,Dangerous Minds,Drama,1995
7,40,"Cry, the Beloved Country",Drama,1995
8,43,Restoration,Drama,1995
9,55,Georgia,Drama,1995
10,57,Home for the Holidays,Drama,1995
11,62,Mr. Holland's Opus,Drama,1995
12,65,Bio-Dome,Comedy,1996
13,69,Friday,Comedy,1995
14,71,Fair Game,Action,1995
15,77,Nico Icon,Documentary,1995
16,88,Black Sheep,Comedy,1996
17,99,Heidi Fleiss: Hollywood Madam,Documentary,1995
18,102,Mr. Wrong,Comedy,1996
19,104,Happy Gilmore,Comedy,1996
20,108,Catwalk,Documentary,1996
21,114,Margaret's Museum,Drama,1995
22,116,Anne Frank Remembered,Documentary,1995
23,119,"Steal Big, Steal Little",Comedy,1995
24,121,"Boys of St. Vincent, The",Drama,1992
25,124,"Star Maker, The (Uomo delle stelle, L')",Drama,1995
26,125,Flirting With Disaster,Comedy,1996
27,130,Angela,Drama,1995
28,132,Jade,Thriller,1995
29,135,Down Periscope,Comedy,1996
...,...,...,...,...
2727,149590,Standoff,Thriller,2016
2728,150856,Making a Murderer,Documentary,2015
2729,152025,SOMM: Into the Bottle,Documentary,2016
2730,152057,Miles Ahead,Drama,2016
2731,152077,10 Cloverfield Lane,Thriller,2016
2732,152091,The Brothers Grimsby,Comedy,2016
2733,152173,Michael Jackson's Thriller,Horror,1983
2734,152844,Demons,Horror,1971
2735,153584,The Last Days of Emma Blank,Comedy,2009
2736,155392,"Hello, My Name Is Doris",Drama,2016
2737,155611,Life Is Sacred,Documentary,2014
2738,155820,Keanu,Comedy,2016
2739,156387,Sing Street,Drama,2016
2740,156609,Neighbors 2: Sorority Rising,Comedy,2016
2741,156726,Hush,Thriller,2016
2742,157667,Mother's Day,Comedy,2016
2743,158314,Daniel Tosh: Completely Serious,Comedy,2007
2744,159462,The Video Dead,Horror,1987
2745,159755,Popstar: Never Stop Never Stopping,Comedy,2016
2746,159858,The Conjuring 2,Horror,2016
2747,160438,Jason Bourne,Action,2016
2748,160440,The Maid's Room,Thriller,2014
2749,160567,Mike & Dave Need Wedding Dates,Comedy,2016
2750,160590,Survive and Advance,(no genres listed),2013
2751,160656,Tallulah,Drama,2016
2752,160718,Piper,Animation,2016
2753,161084,My Friend Rockefeller,Documentary,2015
2754,161155,Sunspring,Sci-Fi,2016
2755,161944,The Last Brickmaker in America,Drama,2001
2756,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,2016

In [7]:
# PROBLEM 5
# What are the top 5 most-reviewed movies?
# Show me a dataframe containing movie title, release year and number of unique user reviews for these five movies.
# Use any Python/pandas method you like!

#
# YOUR CODE HERE
#
top5_movieid = pd.DataFrame(movielens.groupby('title')['userId'].apply(lambda x: len(x.unique())).sort_values(ascending=False)[:5].rename('unique_user_reviews'))
movie_subset = movielens[['title','year']].drop_duplicates()
top5_movies = pd.merge(movie_subset,top5_movieid, how='right',left_on='title',right_index=True).sort_values(by=['unique_user_reviews'],ascending=False).reset_index(drop=True).rename(columns={'title':'movie_title','year':'release_year'})
top5_movies

                           movie_title  release_year  unique_user_reviews
0                        Forrest Gump           1994                  341
1                        Pulp Fiction           1994                  324
2           Shawshank Redemption, The           1994                  311
3           Silence of the Lambs, The           1991                  304
4  Star Wars: Episode IV - A New Hope           1977                  291